ignore:
  - "setup.py"
  - "**/tests/**"
  - "**/examples/**"
coverage:
  range: 80..100
  round: down
  precision: 2
  status:
    project:
      enabled: yes
      target: auto
      threshold: 0%
comment:
  layout: diff, files
  behavior: new
  branches:
    - "master"

