name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Compile and Test 🔨
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make test
      - name: Upload coverage to Codecov 📝
        uses: "codecov/codecov-action@v1"
        with:
          fail_ci_if_error: true
          file: ./coverage-reports/coverage-report.xml