name: deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Package and publish to PyPi 📦
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv setuptools wheel twine
      - name: Build
        run: |
          pipenv run python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to Test PyPI
        if: contains(github.ref, 'beta')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/
  #    - name: Publish distribution 📦 to PyPI
  #        if: (contains(github.ref, 'beta')) != true
  #        uses: pypa/gh-action-pypi-publish@master
  #        with:
  #          password: ${{ secrets.PYPI_PASSWORD }}